### ISSUE TITLE
Xwakes: ComponentResonator missing _source_moment_exponents

### ISSUE THREAD

**Issue by LodeWardVanhecke** [xsuite/xsuite#775]
In Xsuite 0.46.4, calling WakeResonator.track(p) after WakeResonator.calling configure_for_tracking fails with:

```AttributeError: 'ComponentResonator' object has no attribute '_source_moment_exponents'```

The error seems to originate from: xfields/beam_elements/waketracker/convolution.py Specifically, in _ConvData.track(), when accessing: self.component._source_moment_exponents on a ComponentResonator instance.

The exact same code works with xsuite 0.45.5, so this appears to be issue introduced between 0.45.5 and 0.46.4.

Environment
Python==3.12.12
xcoll==0.9.7
xdeps==0.10.11
xfields==0.25.9
xobjects==0.5.12
xpart==0.23.8
xtrack==0.99.4
xwakes==0.2.7
working version: xsuite==0.45.5
failing version: xsuite==0.46.4

Reproducable error:
```python
import numpy as np
import xwakes as xw
import xtrack as xt

w = xw.WakeResonator(r=1e8, q=1e7, f_r=1e8,
    kind='dipolar_x')

w.configure_for_tracking(zeta_range=(-1, 1), num_slices=100)

p = xt.Particles(p0c=7e12, zeta=np.linspace(-1, 1, 1000))
p.x += 1e-3
p.y += 1e-3

w.track(p)
```

**Comment by giadarol** [comment]
Works now. Don't hesitate to reopen if you still see issues
